### ISSUE TITLE
Failure when configuring libcutl for build

### ISSUE THREAD

**Issue by carlossless** [Max13/homebrew-odb#10]
Welp, that doesn't work and I couldn't get to the reason why. Here's the build log.

```
==> Installing odb from max13/odb
==> Installing dependencies for max13/odb/odb: libcutl, libodb
==> Installing max13/odb/odb dependency: libcutl
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/max13/homebrew-odb/libcutl.rb:21:in `<class:Libcutl>'
Please report this to the max13/odb tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/max13/homebrew-odb/libcutl.rb:21:in `<class:Libcutl>'
Please report this to the max13/odb tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/max13/homebrew-odb/libcutl.rb:21:in `<class:Libcutl>'
Please report this to the max13/odb tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/max13/homebrew-odb/libcutl.rb:21:in `<class:Libcutl>'
Please report this to the max13/odb tap!

==> Downloading http://www.codesynthesis.com/download/libcutl/1.9/libcutl-1.9.0.tar.gz
Already downloaded: /Users/mindw0rk/Library/Caches/Homebrew/libcutl-1.9.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/libcutl/1.9.0
Last 15 lines from /Users/mindw0rk/Library/Logs/Homebrew/libcutl/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking how to create a ustar tar archive... gnutar
checking for style of include used by make... none
checking for gcc... gcc-7
checking whether the C compiler works... no
configure: error: in `/private/tmp/libcutl-20170829-81998-1t37l9n/libcutl-1.9.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk" cannot be located.
clang: error: unable to find utility "clang", not a developer tool or in PATH

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/max13/homebrew-odb/issues

These open issues may also help:
unable to open file '/usr/local/Cellar/odb/2.' or read failure https://github.com/Max13/homebrew-odb/issues/9
```

I tried forcing it to use gcc, but still when running `configure` it couldn't produce a binary. The 
`"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk" cannot be located.` is probably the culprit. But I check the directory and it does exist and it contains the 10.12 sdk.

**Comment by Max13** [comment]
Hi @carlossless, do you have Xcode installed ?

EDIT: Sorry, you should have as you have homebrew... Let me check something else.
